//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicOrganizer.Models.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class albums
    {
        public decimal album_id { get; set; }
        public string title { get; set; }
        public decimal artist_id { get; set; }
        public string Picture { get; set; }
        public string TrackCount { get; set; }
        public decimal track_id { get; set; }
    
        public virtual tracks tracks { get; set; }
        public virtual artists artists { get; set; }
    }
}
