//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicOrganizer.Models.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class albums
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public albums()
        {
            this.tracks = new HashSet<tracks>();
        }
    
        public decimal album_id { get; set; }
        public decimal artist_id { get; set; }
        public string title { get; set; }
        public string Picture { get; set; }
        public string TrackCount { get; set; }
    
        public virtual artists artists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tracks> tracks { get; set; }
    }
}
