//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicOrganizer.Models.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracks
    {
        public decimal track_id { get; set; }
        public decimal album_id { get; set; }
        public decimal artist_id { get; set; }
        public string track_title { get; set; }
        public System.TimeSpan duration { get; set; }
        public int album_position { get; set; }
        public string composer { get; set; }
        public string description { get; set; }
        public int disc_number { get; set; }
        public string genre { get; set; }
        public string lyricist { get; set; }
        public int bpm { get; set; }
        public string filepath { get; set; }
    
        public virtual albums albums { get; set; }
        public virtual artists artists { get; set; }
    }
}
